# Generated by Django 3.2.9 on 2021-11-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['created_at'], name='todos_todo_created_596622_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['updated_at'], name='todos_todo_updated_8020c6_idx'),
        ),
    ]
